### ISSUE TITLE
Extract type cast behaviour

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-doctrine-querybuilder#1]
By extracting the type casting to its own class it can be easily replaced when needed. Preferring composition over inheritance etc.

 It becomes better testable as well.

I tried to keep BC by proxying to the TypeCaster and instantiating the TypeCaster in the AbstractFilter::getTypeCaster() method when not set in case FilterManager::filter() method is overridden.

---

Originally posted by @netiul at https://github.com/zfcampus/zf-doctrine-querybuilder/pull/57

**Comment by weierophinney** [comment]
[![Coverage Status](https://coveralls.io/builds/25731879/badge)](https://coveralls.io/builds/25731879)

Coverage decreased (-66.2%) to 14.427% when pulling **b20a1a0cf296ec374d34033861fd91c2c8e23bf8 on netiul:feature/extract-type-casting** into **cca97a6f375160660e1305bc610d0fc135b9bd6c on zfcampus:master**.


---

Originally posted by @coveralls at https://github.com/zfcampus/zf-doctrine-querybuilder/pull/57#issuecomment-531905072

**Comment by michalbundyra** [comment]
See: #5
