### ISSUE TITLE
Create Docker environment for testing

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-doctrine-querybuilder#4]
Use zf-apigility-doctrine as a templete.

https://github.com/zfcampus/zf-apigility-doctrine/pull/308

---

Originally posted by @TomHAnderson at https://github.com/zfcampus/zf-doctrine-querybuilder/issues/47

**Comment by TomHAnderson** [comment]
Done in #6 #7

**Comment by TomHAnderson** [comment]
PR #6 #7 have been closed.  Recommend closing this issue.
